// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SQLJS from "./bindings/SQLJS.mjs";
import * as React from "react";

function App(Props) {
  React.useEffect((function () {
          var loadSQLJS = async function (param) {
            console.log("load sql.js");
            var sql = await SQLJS.init(function (file) {
                  return "https://sql.js.org/dist/" + file + "";
                });
            debugger;
            var db = await SQLJS.loadDatabase(sql);
            var res = db.exec("SELECT * FROM reviews;");
            console.log(res);
          };
          loadSQLJS(undefined);
        }), []);
  return React.createElement("div", undefined, "testing");
}

var make = App;

export {
  make ,
}
/* SQLJS Not a pure module */
