// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TNDStatsDB from "./TNDStatsDB.mjs";
import * as ReviewsTable from "./ReviewsTable.mjs";

function App(Props) {
  return React.createElement(TNDStatsDB.Provider.make, {
              children: React.createElement(ReviewsTable.make, {})
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
