// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TNDStatsDB from "./TNDStatsDB.mjs";
import * as ChartByGenre from "./ChartByGenre.mjs";
import * as ReviewsTable from "./ReviewsTable.mjs";
import * as ChartRankByYear from "./ChartRankByYear.mjs";

function App(Props) {
  return React.createElement(TNDStatsDB.Provider.make, {
              children: null
            }, React.createElement(ChartByGenre.make, {}), React.createElement(ReviewsTable.make, {}), React.createElement(ChartRankByYear.make, {}));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
