// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as Client from "react-dom/client";

function Root$ReactApp(Props) {
  return React.createElement(App.make, {});
}

var ReactApp = {
  make: Root$ReactApp
};

var element = document.querySelector("#root");

if (!(element == null)) {
  var root = Client.createRoot(element);
  root.render(React.createElement(Root$ReactApp, {}));
}

export {
  ReactApp ,
}
/* element Not a pure module */
